services:
  # OPENSEARCH
  opensearch-server:
    image: opensearchproject/opensearch:3.2.0
    container_name: opensearch-server
    hostname:       opensearch-server

    environment:
      cluster.name: opensearch-server
      node.name:    opensearch-server
      discovery.type: single-node

      plugins.security.allow_default_init_securityindex: 'true'
      plugins.security.allow_unsafe_democertificates:    'false'
      plugins.security.nodes_dn:        'CN=admin'
      plugins.security.authcz.admin_dn: 'CN=admin'

      plugins.security.ssl.http.enabled: 'true'
      plugins.security.ssl.http.pemkey_filepath:        certificates/key/server.key
      plugins.security.ssl.http.pemcert_filepath:       certificates/crt/server.crt
      plugins.security.ssl.http.pemtrustedcas_filepath: certificates/crt/server.crt

      plugins.security.ssl.transport.enabled: 'true'
      plugins.security.ssl.transport.pemkey_filepath:        certificates/key/server.key
      plugins.security.ssl.transport.pemcert_filepath:       certificates/crt/server.crt
      plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/crt/server.crt
      plugins.security.ssl.transport.enforce_hostname_verification: 'false'
      plugins.security.ssl.http.clientauth_mode: OPTIONAL

      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      logger.level: INFO

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./configs/opensearch/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml:ro
      - ./configs/opensearch/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml:ro
      - ./configs/opensearch/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml:ro
      - ./ssl:/usr/share/opensearch/config/certificates:ro
      - opensearch-server:/usr/share/opensearch/data

    ports:    ['9200:9200', '9600:9600']
    networks: ['opensearch-net']
    restart: unless-stopped

  # DASHBOARDS
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.2.0
    container_name: opensearch-dashboards
    hostname:       opensearch-dashboards
    environment:
      SERVER_NAME: opensearch-dashboards
      SERVER_HOST: 0.0.0.0

      OPENSEARCH_USERNAME: kibanaserver
      OPENSEARCH_PASSWORD: a12345678

      OPENSEARCH_HOSTS: '["https://opensearch-server:9200"]'

      DISABLE_INSTALL_DEMO_CONFIG: 'true'

    volumes:
      - ./ssl:/usr/share/opensearch-dashboards/config/certificates:ro
      - ./configs/opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml

    ports:    ['5601:5601']
    networks: ['opensearch-net']
    restart: unless-stopped


volumes:
  opensearch-server:
    name: opensearch-server

networks:
  opensearch-net:
    external: true
    name: my_network #docker network create my_network
