---
_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    do_not_fail_on_forbidden: true
    do_not_fail_on_forbidden_empty: true
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "intern"
      saml_auth_domain:
        order: 1
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              entity_id: "http://keycloak:8080/realms/boundary"
              metadata_url: "http://keycloak:8080/realms/boundary/protocol/saml/descriptor"
            # sp:
            #   entity_id: "http://opensearch-dashboards:5601"     # MUST match TF client_id
            # kibana_url: "http://opensearch-dashboards:5601"  # or https://localhost:5601 if you enable TLS in Dashboards
            roles_key: "groups"
            exchange_key: "9b4a1c4a3d6f0f1a2b3c4d5e6f7a8b9c9b4a1c4a3d6f0f1a2b3c4d5e6f7a8b9"
        authentication_backend:
          type: noop
