---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth_domain:
        order: 1
        description: "SAML provider"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: http://keycloak:8080/realms/boundary/protocol/saml/descriptor
              entity_id: http://keycloak:8080/realms/boundary
            sp:
              entity_id: http://opensearch-dashboards:5601
            kibana_url: http://opensearch-dashboards:5601
            roles_key: groups
            exchange_key: bdf50723fdc410f9bb5e23920af3b9b4b81868d88e7da4e194a5105c2da3cf3a
        authentication_backend:
          type: noop
